spring.config.activate.on-profile: local
#
#spring:
#  jpa:
#    open-in-view: false
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
#      hibernate.default_batch_fetch_size: 100
#  h2:
#    console:
#      enabled: true
#
#storage:
#  datasource:
#    core:
#      driver-class-name: org.h2.Driver
#      jdbc-url: jdbc:h2:mem:core;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#      username: sa
#      pool-name: core-db-pool
#      data-source-properties:
#        rewriteBatchedStatements: true

---

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_log: true
        format_sql: true
      hibernate.default_batch_fetch_size: 100
    show-sql: true

storage:
  datasource:
    core:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/lecture
      username: root
      password: 1234
